### ISSUE TITLE
BungeeTabListPlus placeholder Registrierung

### ISSUE THREAD

**Issue by RedstoneFuture** [RedstoneWorld/RedPlayerInfo#5]
Ich hab die Tage auch mal BungeeTabListPlus auf die Version 3.2.2 geupdatet.

https://pastebin.com/EgNmyFeN

Momentan wird erst BungeeTabListPlus geladen und dann erst RedPlayerInfo, was zu Folge hat, dass die BTLP sich beschwert die eingetragenen Placeholder nicht zu kennen.

_getestet mit build #65_

```
05.26-04:54:59 [WARNUNG] [BungeeTabListPlus] There have been 6 warnings while loading plugins/BungeeTabListPlus/tabLists/default.yml
WARNING: Error in placeholder ${player red_afk}:
[...]
05.26-04:54:59 [INFORMATION] [RedPlayerInfo] Registered AfkPlaceholderVariable
```

**Comment by Phoenix616** [comment]
Variablen sollten trotzdem funktioniert haben, hab aber mal die Registrierung der Variable in die onLoad Methode verschoben. Die Reiheifolge zu ändern würde nicht funktionieren da ja sonst RedPlayerInfo lädt bevor BTLP verfügbar ist.

**Comment by RedstoneFuture** [comment]
ab Build 67:

```
06.03-04:24:47 [INFORMATION] [BungeeTabListPlus] Starting UpdateChecker Task
06.03-04:24:47 [INFORMATION] Enabled plugin BungeeTabListPlus version 3.2.2 by CodeCrafter47
06.03-04:24:48 [WARNUNG] Exception encountered when loading plugin: RedPlayerInfo
java.lang.NullPointerException
	at de.redstoneworld.redplayerinfo.bungee.PluginCommand.<init>(PluginCommand.java:51)
	at de.redstoneworld.redplayerinfo.bungee.commands.RedAfkCommand.<init>(RedAfkCommand.java:12)
	at de.redstoneworld.redplayerinfo.bungee.RedPlayerInfo.onEnable(RedPlayerInfo.java:56)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:247)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:279)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
```
